name: Bump footer version/date

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read version and set date
        id: meta
        run: |
          if [ ! -f VERSION ]; then
            echo "VERSION file missing"; exit 1
          fi
          echo "version=$(cat VERSION | tr -d '\r' | tr -d ' \t')" >> $GITHUB_OUTPUT
          echo "date=$(date -u +%F)" >> $GITHUB_OUTPUT

      - name: Show current footer (if any)
        run: |
          echo "Searching for footer line…"
          # Show lines that contain 'Version v' for debugging
          grep -nR "Version v" index.html || echo "No 'Version v' line found in index.html"

      - name: Update footer in index.html
        run: |
          v="${{ steps.meta.outputs.version }}"
          d="${{ steps.meta.outputs.date }}"
          # Accept • or &bull; or - or — and flexible whitespace
          perl -0777 -pe "s/Version\s+v[0-9.]+\s*(?:•|&bull;|-|—)\s*Last\s+updated\s*\d{4}-\d{2}-\d{2}/Version v${v} • Last updated ${d}/g" -i index.html

      - name: Commit changes (if any)
        run: |
          if git diff --quiet; then
            echo "No footer changes to commit."
            exit 0
          fi
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "chore: bump footer to v${{ steps.meta.outputs.version }} on ${{ steps.meta.outputs.date }} [skip ci]"
          git push
